### PR TITLE
Add support of LIC0

### PR DESCRIPTION
**Pull request by apeinot**
Add function and test for the launch input condition number 0

Solve issue #1

### CODE REVIEW

**Comment by francislaus** [comment]
After analyzing your code, I think that it is pretty good and solves #1 correctly

**Comment by emilelm96** [comment]
It's good and solves #1. I don't want to be pedantic, but if we want to follow the commenting convention and be consistent, the comment should be above the function. We also decided upon no asterisks in between /** and the */, I think. You can use @return since having an explicit return tag makes it easier for someone to find the return value quickly. Even though the description is quite short here I think it's a principle we should follow.

**Comment by apeinot** [comment]
I have made a new commit to fix what you said. Tell me if it's ok before I can merge. It should solve #1

**Comment by emilelm96** [comment]
Yes, that is excellent. Solves #1.

**Comment by apeinot** [comment]
Solve #1. I merge it.

**Pull request merged**
