### PR TITLE
Issue10

### PR DESCRIPTION
**Pull request by Samuelhertzberg**
Support for LIC9 and tests.

### CODE REVIEW

**Comment by francislaus** [comment]
I think your function has a bug. By execution all your tests and printing the computed angles to stdout, you can see that you always compute the same angle no matter which input data you have. Another hint: Be aware that acos() does only compute angles from 0 to PI (so you have to check whether angle = x holds or whether it is angle = 2 * PI - x). I really like your testing. You cover a lot of edge cases!

**Comment by Samuelhertzberg** [comment]
There is definitely something wrong as if i test three point all on the x-axis it still says angle = PI/2. However I don't think the range of acos is a problem. The *inner* angle of three points also has range 0 - PI right?

**Comment by Samuelhertzberg** [comment]
Or maybe this thinking is flawed. As one of the criteria is angle > PI+Epsilon. If the angle can never exceed PI this will never be fulfilled.

**Comment by apeinot** [comment]
I suggest you take a look to what Franz did for LIC 2 in pull request #32 (It's the same angle computation and Franz implementation works fine)

**Comment by Samuelhertzberg** [comment]
Yes, I shamelessly copied your cross-product check. Thanks.

**Comment by francislaus** [comment]
I think that your implementation closes #10 now and also provides good testing.

**Comment by Jonagoo** [comment]
Method and tests look good.

**Pull request merged**
