### PR TITLE
Added support of LIC3

### PR DESCRIPTION
**Pull request by emilelm96**
Added functions and tests for the third launch input condition

Solve issue #6.

### CODE REVIEW

**Comment by francislaus** [comment]
Your code solves #6. I really like the way you did the inline comments and the way you coded the test. It covers a lot of possible input data for LIC3(). I also do not want to do hairsplitting here, but I think that we should do two part commit messages (In the first line the title and from the third line on a more detailed description).

**Comment by apeinot** [comment]
Your function and tests solve well #6. However, you forget to add a description in your commit message. Please do that in the future.

**Comment by emilelm96** [comment]
I just remembered that I should probably check if AREA1 >= 0 as well, since it's one of the requirements of this LIC.

**Comment by emilelm96** [comment]
Now everything should be in order.

**Comment by apeinot** [comment]
Look's good. I will resolve the conflicts and merge it

**Pull request merged**
