### PR TITLE
Added implementation to compute PUM

### PR DESCRIPTION
**Pull request by francislaus**
Added function computePUM to implement the computation of the matrix PUM and two corresponding test functions.

This solves #16

### CODE REVIEW

**Comment by apeinot** [comment]
The function and the tests are fine and address the right issue. Please add comment on each test according to what is describe here https://www.monperrus.net/martin/introduction-unit-tests

**Comment by Jonagoo** [comment]
computePUM() looks good, but lines 71 through 73 don't have any function as j is initialized to i+1 and thus will never be equal in the first place. As mentioned previously, some comments for the tests are needed.

**Comment by emilelm96** [comment]
Great clean implementation and exhaustive testing, although I agree that some comments wouldn't hurt.

**Comment by apeinot** [comment]
It's fine and well describe. I will resolve the conflict and merge it to resolve #16

**Pull request merged**
