### PR TITLE
Added function computeLAUNCH for #18

### PR DESCRIPTION
**Pull request by francislaus**
Added the implementation of the function computeLAUNCH and the implementation of the corresponding test function

### CODE REVIEW

**Comment by apeinot** [comment]
Good code and tests. That should resolve #18

**Comment by Samuelhertzberg** [comment]
I agree with @apeinot, resolve #18

**Comment by Samuelhertzberg** [comment]
I really like the "LAUNCH = LAUNCH && FUV[i];" way of setting conditions in a loop. Clean.

**Comment by apeinot** [comment]
I will resolve the conflicts and merge it to close #18

**Pull request merged**
