### PR TITLE
fix #15: Added functionality and tests for LIC10.

### LINKED ISSUE #15: Add LIC 10
There exists at least one set of three data points separated by exactly **E_PTS** and **F_PTS** consecutive intervening points, respectively, that are the vertices of a triangle with area greater
than **AREA1**. The condition is not met when **NUMPOINTS** < 5.
1 ≤ **E_PTS**, 1 ≤ **F_PTS**
**E_PTS**+**F_PTS** ≤ **NUMPOINTS**−3

### PR DESCRIPTION
**Pull request by emilelm96**
Assesses if there exists at least one set of three data points separated by exactly E_PTS and F_PTS consecutive intervening points, respectively, that are the vertices of a triangle with area greater than AREA1 (PARAMETERS.AREA1).

### CODE REVIEW

**Review by apeinot — COMMENTED** [review]
Your function and test cases are fine. Two things to fix:
- In LIC10() function, the indentation of the for loop is not could (should be at the same level as the if)
- Your test function is named "testLIC3" instead of "testLIC10"

**Comment by Samuelhertzberg** [comment]
Apart from what @apeinot wrote I would like to add some miner things. The bad data if statement should(in my opinion) have brackets unless we have said that no-bracket-statements are fine. Also the first/second/third_point int varaibles seem borderline unnecessary. Normally this would be fine, but as it is inside a loop, declaration of a lot of variables is bad.

**Comment by emilelm96** [comment]
Now everything should be fine. Please review it so we can merge it.

**Comment by apeinot** [comment]
Seems ok. I will resolve the conflicts and merge it

**Pull request merged**
